#### Methodology

Our group currently has access to restricted-access NCHS natality records from
1989-2016. To achieve this Aim and address the four critical areas described above, we will estimate (and
map) the prevalence of very preterm birth (<32 weeks); late preterm birth (34-36 weeks); and preterm birth
(<37 weeks) for each U.S. county overall, and for non-Hispanic White and non-Hispanic Black women
separately. 

We will further estimate (and map) the county-specific Black-White relative and absolute
disparities. To produce stable and valid estimates of both the risks and the disparity measures we will
implement spatial Bayesian disease mapping techniques, which ‘borrow’ statistical strength for spatiotemporal
dependencies (9–11). These have been widely validated, are frequently used, and my team has used them for
estimating perinatal and mortality parameters in US counties(12–16). 

While some counties will still be
suppressed (e.g. there are no Black births in many counties), the number of counties with estimates is
substantially higher with these methods than when following NCHS suppression rules, and all estimates are
more valid than approaches ignoring data sparseness (10).
