# **Mapping the Social Epidemiology of Preterm Birth**

<br>

Despite decades of clinical and population research, the problem of large and unacceptable racial,
economic, and geographic disparities in preterm birth persist(1,2). As a perinatal and social epidemiologist, Dr.
Kramer has been a leader advancing empirical research, advanced analytic methods, and interdisciplinary
research focused specifically on racial and geographic disparities in women’s and children’s health, and
preterm birth in particular. He has published 38 peer-reviewed papers and 3 book chapters on health equity
and pregnancy outcomes, and 46 peer-reviewed papers and 3 book chapters on broader maternal and child
health outcomes, health equity, and geosocial epidemiology.

<br>

Inadequate integration of theoretical and methodological insight from clinical, epidemiologic, and social
science research impedes progress towards impactful action to eliminate inequity in preterm birth and other
perinatal outcomes. This project is a multi-step workflow aimed to lay the groundwork for
next steps in the March of Dimes Center for Social Science Research. Specifically focusing on goals to
***estimate, associate, and disseminate***, this project is designed as a jumping off point for further
conversations in the role of consultant research with March of Dimes.