## **Aim 1:** ***Estimate*** *and map valid small area indicators of preterm birth equity in US counties.* {.tabset}

### Motivation

In this aim, four vital areas rarely all incorporated into research on
geography of preterm birth disparities are addresed, but which together strengthen the resulting inference. 

  1.  Perinatal epidemiology has detailed how heterogeneous preterm birth defined as all births <37 weeks is (e.g. in terms of diverse biological pathways and clinical presentation). As a result, uncritical use of <37 weeks as a target parameter in population research may mask important findings or patterns which are restricted to specific
subsets (e.g. very preterm birth or spontaneous preterm birth)(3–5). 

  2.  Social epidemiology and health
geography have illustrated substantial small area variation in population health arising from local variation in
social and economic context. Counties represent the smallest consistently defined geographic unit at which
social policy can be implemented and resources allocated (6,7). 

  3.  This third area is a consequence of the
second, and that is attention to valid estimation of health outcomes for small populations (e.g. race groups
within sparsely populated counties). Much past research has ignored instability from sparse event counts likely
biasing findings not only from measurement error, but from the socially-selected nature of the sparse data.

  4.  Fourth, health equity scholars are often uncritical of the choice of measure of ‘disparity’, relying most often on
the ‘relative excess’ or risk ratio approach (e.g. Black women have 1.5 times the risk of PTB as White women).As Harper, et al (8) observe, measures of ‘equity’ are inherently value laden, and inattention to a measures’
implicit values diminishes clarity at best, and can give frankly incorrect answers in some instances. For
example, relative measures emphasize proportionate deviations from equality; alternatively absolute
differences in PTB risk emphasizes the absolute excess burden experienced by one group and speak to the
number of lives impacted by prematurity.

### Methodology

Our group currently has access to restricted-access NCHS natality records from
1989-2016. To achieve this Aim and address the four critical areas described above, we will estimate (and
map) the prevalence of very preterm birth (<32 weeks); late preterm birth (34-36 weeks); and preterm birth
(<37 weeks) for each U.S. county overall, and for non-Hispanic White and non-Hispanic Black women
separately. 

We will further estimate (and map) the county-specific Black-White relative and absolute
disparities. To produce stable and valid estimates of both the risks and the disparity measures we will
implement spatial Bayesian disease mapping techniques, which ‘borrow’ statistical strength for spatiotemporal
dependencies (9–11). These have been widely validated, are frequently used, and my team has used them for
estimating perinatal and mortality parameters in US counties(12–16). 

While some counties will still be
suppressed (e.g. there are no Black births in many counties), the number of counties with estimates is
substantially higher with these methods than when following NCHS suppression rules, and all estimates are
more valid than approaches ignoring data sparseness (10).
