## **Aim 2:** *Explore* ***associations*** *between family economic and social opportunity and stress and preterm birth.* {.tabset}

### Motivation

Identifying plausible causal contributors to preterm birth, and to racial and geographic
disparities in PTB specifically, requires more than a list of statistical correlations with a jumble of contextual
indicators. 

Social theory points to the importance of fundamental drivers of between-race access to material,
social, and human capital as necessary for the reproduction of disparity observed in preterm birth (17).

Epidemiologic theory points to the distinction between the ‘causes of cases’ (e.g. individual risk factors) and
the ‘causes of causes’ (e.g. contextual determinants of between-group difference) (18), with the latter being of
critical importance for investigating racial disparities.

### Methodology

We have assembled a unique set of county-level indicators of social and economic
context that represent potentially policy-modifiable factors that could vary by race and geography, and that are
plausibly related to known pathways to preterm birth (e.g. they may influence social support, chronic economic
stress, and lack of quality health care). 

The indicators include measures of:

  + Material capital (e.g. median household income, poverty rate)
  + Social capital (e.g. crime rate, % housing instability/turnover) 
  + Human capital (e.g. % unemployed, % changed jobs in last year, % at various levels attained education) 
  + Local measures of economic fragility (e.g. % food insecure, cost of living including % spending >30% on housing)
  + Economic safety net (e.g. % WIC, % SNAP, % of tax returns with EITC). 
  
These data come from PolicyMap.org, the Census Bureau, and other aggregators of demographic and economic data. 

We explore associations between these contextual variables and preterm birth (overall and by race) to understand how these factors affect prevalence. Separately, we examine the association of contextual variables with the *magnitude* of the Black-White disparity (relative or absolute) to identify correlates of between-group variance.