## Literature Cited

1.  Martin JA, Osterman MJK. Describing the Increase in Preterm Births in the United States, 2014-2016. Vol. no 312, NCHS Data Brief. Hyattsville, MD; 2018.
2. Martin JA, Hamilton BE, Ph D, Osterman MJK, Driscoll AK, Ph D, et al. Births: Final Data for 2016. Vol.
67, National Vital Statistics Reports. Hyattsville, MD; 2018.
3. Kramer MR, Hogue CR. What causes racial disparities in very preterm birth? A biosocial perspective.
Epidemiol Rev [Internet]. 2009 Jan;31(1):84–98. Available from:
http://www.ncbi.nlm.nih.gov/pubmed/19477907
4. Behrman RE, Butler AS. Preterm Birth: Causes, Consequences, and Prevention - PubMed - NCBI
[Internet]. Washington, DC; 2007 [cited 2016 Jan 24]. Available from:
http://www.ncbi.nlm.nih.gov/pubmed/20669423
5. Goldenberg RL, Culhane JF, Iams JD, Romero R. Epidemiology and causes of preterm birth. Lancet
(London, England) [Internet]. 2008 Jan 5;371(9606):75–84. Available from:
http://www.ncbi.nlm.nih.gov/pubmed/18177778
6. Allen DW. Social class, race, and toxic releases in American counties, 1995. Soc Sci J [Internet]. 2001
Mar [cited 2016 Apr 1];38(1):13–25. Available from:
http://www.sciencedirect.com/science/article/pii/S0362331900001099
7. Lobao LM. The Emerging Roles of County Governments in Metropolitan and Nonmetropolitan Areas:
Findings From a National Survey. Econ Dev Q [Internet]. 2005 Aug 1 [cited 2016 Apr 1];19(3):245–59.
Available from: http://edq.sagepub.com/content/19/3/245.abstract
8. Harper S, King NB, Meersman SC, Reichman ME, Breen N, Lynch J. Implicit value judgments in the
measurement of health inequalities. Milbank Q [Internet]. 2010 Mar;88(1):4–29. Available from:
http://www.ncbi.nlm.nih.gov/pubmed/20377756
9. Kirby RS, Liu J, Lawson AB, Choi J, Cai B, Hossain M. Spatio-temporal patterning of small area low
birth weight incidence and its correlates: A latent spatial structure approach. Spat Spatiotemporal
Epidemiol. 2011;2(4):265–71.
10. Banerjee S, Carlin B, Gelfand A. Hierarchical modeling and analysis for spatial data [Internet]. 2014
[cited 2017 Jan 23]. Available from:
https://books.google.com/books?hl=en&lr=&id=WVHRBQAAQBAJ&oi=fnd&pg=PP1&dq=carlin+brad+ba
yesian+text&ots=AnA1sjPHlZ&sig=-baWaXrEUNTtJxVKmiwY92JACnE
11. Waller L, Gotway C. Applied Spatial Statistics for Public Health Data. Hoboken, NJ: John Wiley & Sons,
Inc; 2004.
12. Kramer MR, Williamson R. Multivariate bayesian spatial model of preterm birth and cardiovascular
disease among georgia women: Evidence for life course social determinants of health. Spat
Spatiotemporal Epidemiol [Internet]. 2013 Sep;6:25–35. Available from:
http://linkinghub.elsevier.com/retrieve/pii/S1877584513000294
13. Kramer MR, Cooper HL, Drews-Botsch CD, Waller LA, Hogue CR. Metropolitan isolation segregation
and Black-White disparities in very preterm birth: a test of mediating pathways and variance explained.
Soc Sci Med [Internet]. 2010 Dec [cited 2014 Aug 12];71(12):2108–16. Available from:
http://www.pubmedcentral.nih.gov/articlerender.fcgi?artid=2992580&tool=pmcentrez&rendertype=abstra
ct
14. Kramer MRMR, Raskind IGIG, Van Dyke MEME, Matthews SASA, Cook-Smith JNJN. Geography of
Adolescent Obesity in the U.S., 2007-2011. Am J Prev Med [Internet]. 2016 Dec;51(6):898–909.
Available from: http://linkinghub.elsevier.com/retrieve/pii/S0749379716302458
15. Casper M, Kramer MR, Quick H, Schieb LJ, Vaughan AS, Greer S. Changes in the Geographic Patterns
of Heart Disease Mortality in the United States: 1973 to 2010. Circulation [Internet]. 2016 Mar22;133(12):1171–80. Available from: http://www.ncbi.nlm.nih.gov/pubmed/27002081
16. Vaughan AS, Kramer MR, Waller L a., Schieb LJ, Greer S, Casper M. Comparing methods of measuring
geographic patterns in temporal trends: an application to county-level heart disease mortality in the
United States, 1973 to 2010. Ann Epidemiol [Internet]. 2015;25(5):329–335.e3. Available from:
http://linkinghub.elsevier.com/retrieve/pii/S1047279715000538
17. Link BG, Northridge ME, Phelan JC, Ganz ML. Social epidemiology and the fundamental cause
concept: on the structuring of effective cancer screens by socioeconomic status. Milbank Q [Internet].
1998;76(3):375–402, 304–5. Available from: http://www.ncbi.nlm.nih.gov/pubmed/9738168
18. Rose G. Sick individuals and sick populations. Vol. 30, International journal of epidemiology. 2001. p.
427–32.